# -*- coding: utf-8 -*-
"""Phase1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18TsUiEdiwqV4pcyHuwkyRpFdEYxZWBMf

### Phase 1: Power Plant Steam Turbine Optimization
We will load the training dataset, train several polynomial regression models to find the optimal degree, evaluate performance, and generate predictions on the test dataset.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import KFold
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import Ridge
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, r2_score


# =====================================================================
# CONFIGURATION
# =====================================================================
ROLL_NO = "IMT2024043"

print(f"Configured Roll Number: {ROLL_NO}")

# =====================================================================
# 1. LOAD DATASET
# =====================================================================

train_var1_file = f"{ROLL_NO}_train_var1.csv"
test_var1_file = f"{ROLL_NO}_test_var1.csv"

train_df_var1 = pd.read_csv(train_var1_file)
test_df_var1 = pd.read_csv(test_var1_file)

print("Training data shape:", train_df_var1.shape)
print("Test data shape:", test_df_var1.shape)

display(train_df_var1.head())


# =====================================================================
# 2. SEPARATE FEATURES AND TARGET
# =====================================================================

feature_cols_v1 = [
    c for c in train_df_var1.columns
    if c.startswith("x")
]

X_train_v1 = train_df_var1[feature_cols_v1].values
y_train_v1 = train_df_var1["y"].values

X_test_v1 = test_df_var1[feature_cols_v1].values


# =====================================================================
# 3. HYPERPARAMETERS
# =====================================================================

# Q1: Polynomial degrees 1 to 10
degrees_v1 = list(range(1, 11))

# Ridge regularization strengths
alphas_v1 = np.logspace(-4, 4, 9)

# 5-fold cross-validation
cv_v1 = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)


# =====================================================================
# 4. VARIABLES TO STORE BEST MODEL
# =====================================================================

results_v1 = []

best_cv_mse_v1 = np.inf
best_degree_v1 = None
best_alpha_v1 = None


# =====================================================================
# 5. GRID SEARCH USING 5-FOLD CROSS-VALIDATION
# =====================================================================

print("\n==============================================================")
print("Q1 - RIDGE HYPERPARAMETER SEARCH")
print("Polynomial Degrees : 1 to 10")
print("Regularization     : Ridge")
print("Alpha Values       :", alphas_v1)
print("Cross Validation   : 5-Fold")
print("==============================================================\n")


for degree in degrees_v1:

    print(f"Testing Polynomial Degree: {degree}")

    for alpha in alphas_v1:

        # -------------------------------------------------------------
        # Create Ridge Pipeline
        # -------------------------------------------------------------

        pipeline = Pipeline([
            (
                "poly",
                PolynomialFeatures(
                    degree=degree,
                    include_bias=False
                )
            ),

            (
                "scaler",
                StandardScaler()
            ),

            (
                "ridge",
                Ridge(
                    alpha=alpha,
                    max_iter=50000
                )
            )
        ])

        fold_mse = []

        # -------------------------------------------------------------
        # 5-Fold Cross Validation
        # -------------------------------------------------------------

        for train_idx, val_idx in cv_v1.split(X_train_v1):

            X_train_fold = X_train_v1[train_idx]
            X_val_fold = X_train_v1[val_idx]

            y_train_fold = y_train_v1[train_idx]
            y_val_fold = y_train_v1[val_idx]

            # Train on 4 folds
            pipeline.fit(
                X_train_fold,
                y_train_fold
            )

            # Validate on remaining fold
            y_val_pred = pipeline.predict(
                X_val_fold
            )

            mse = mean_squared_error(
                y_val_fold,
                y_val_pred
            )

            fold_mse.append(mse)

        # Average validation MSE
        mean_cv_mse = np.mean(fold_mse)

        # Store result
        results_v1.append({
            "Degree": degree,
            "Alpha": alpha,
            "CV_MSE": mean_cv_mse
        })

        # -------------------------------------------------------------
        # Check if this is the best combination
        # -------------------------------------------------------------

        if mean_cv_mse < best_cv_mse_v1:

            best_cv_mse_v1 = mean_cv_mse
            best_degree_v1 = degree
            best_alpha_v1 = alpha


# =====================================================================
# 6. RESULTS TABLE
# =====================================================================

results_df_v1 = pd.DataFrame(results_v1)

results_df_v1 = results_df_v1.sort_values(
    by="CV_MSE"
).reset_index(drop=True)


print("\n==============================================================")
print("Q1 - TOP 10 RIDGE MODELS")
print("==============================================================")

display(results_df_v1.head(10))


# =====================================================================
# 7. OPTIMAL MODEL
# =====================================================================

print("\n==============================================================")
print("Q1 - OPTIMAL RIDGE MODEL")
print("==============================================================")

print(f"Optimal Polynomial Degree : {best_degree_v1}")
print(f"Regularization Model     : Ridge")
print(f"Regularization Strength  : {best_alpha_v1}")
print(f"Best 5-Fold CV MSE       : {best_cv_mse_v1:.6f}")


# =====================================================================
# 8. TRAIN FINAL MODEL ON COMPLETE TRAINING DATA
# =====================================================================

final_model_v1 = Pipeline([
    (
        "poly",
        PolynomialFeatures(
            degree=best_degree_v1,
            include_bias=False
        )
    ),

    (
        "scaler",
        StandardScaler()
    ),

    (
        "ridge",
        Ridge(
            alpha=best_alpha_v1,
            max_iter=50000
        )
    )
])


final_model_v1.fit(
    X_train_v1,
    y_train_v1
)


# =====================================================================
# 9. TRAINING PERFORMANCE
# =====================================================================

y_train_pred_v1 = final_model_v1.predict(
    X_train_v1
)

train_mse_v1 = mean_squared_error(
    y_train_v1,
    y_train_pred_v1
)

train_r2_v1 = r2_score(
    y_train_v1,
    y_train_pred_v1
)


print("\n==============================================================")
print("Q1 - FINAL PERFORMANCE")
print("==============================================================")

print(f"Polynomial Degree : {best_degree_v1}")
print(f"Model             : Ridge")
print(f"Alpha             : {best_alpha_v1}")
print(f"CV MSE            : {best_cv_mse_v1:.6f}")
print(f"Training MSE      : {train_mse_v1:.6f}")
print(f"Training R²       : {train_r2_v1:.6f}")


# =====================================================================
# 10. PREDICT TEST DATA
# =====================================================================

y_test_pred_v1 = final_model_v1.predict(
    X_test_v1
)

pred_df_v1 = test_df_var1.copy()

pred_df_v1["y"] = y_test_pred_v1

out_file_v1 = f"{ROLL_NO}_pred_var1.csv"

pred_df_v1.to_csv(
    out_file_v1,
    index=False
)

print(f"\nPredictions saved to: {out_file_v1}")


# =====================================================================
# 11. BEST CV MSE FOR EACH DEGREE
# =====================================================================

degree_summary_v1 = (
    results_df_v1
    .groupby("Degree")["CV_MSE"]
    .min()
    .reset_index()
)

print("\n==============================================================")
print("Q1 - BEST CV MSE FOR EACH DEGREE")
print("==============================================================")

display(degree_summary_v1)


# =====================================================================
# 12. PLOT
# =====================================================================

plt.figure(figsize=(8, 5))

plt.plot(
    degree_summary_v1["Degree"],
    degree_summary_v1["CV_MSE"],
    marker="o",
    linewidth=2
)

plt.axvline(
    best_degree_v1,
    linestyle="--",
    label=f"Optimal Degree = {best_degree_v1}"
)

plt.title(
    "Q1: Best 5-Fold CV MSE vs Polynomial Degree"
)

plt.xlabel("Polynomial Degree")
plt.ylabel("Cross-Validation MSE")

plt.yscale("log")

plt.xticks(degrees_v1)

plt.grid(True)

plt.legend()

plt.show()


# =====================================================================
# 13. FINAL SUMMARY
# =====================================================================

print("\n\n==============================================================")
print("                  Q1 FINAL SUMMARY")
print("==============================================================")

print(f"Optimum Degree          : {best_degree_v1}")
print(f"Regularization Model    : Ridge")
print(f"Regularization Strength : {best_alpha_v1}")
print(f"Best CV MSE             : {best_cv_mse_v1:.6f}")
print(f"Final Training MSE      : {train_mse_v1:.6f}")
print(f"Final Training R²       : {train_r2_v1:.6f}")

print("==============================================================")